<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Updated with clean, professional SOLECRAFT Care Service Catalog.
     */
    public function run(): void
    {
        $services = [
            // SHOES CLEANING REGULAR
            [
                'name' => 'Regular Clean (Warna Gelap)',
                'slug' => 'regular-shoes-dark',
                'description' => 'Pembersihan menyeluruh khusus sneakers & casual bernuansa gelap (hitam, navy, dark brown). Membersihkan upper, midsole, outsole, dan tali sepatu secara higienis.',
                'price' => 45000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Slip-on', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => ['Suede', 'Nubuck'],
                'target_issues' => ['Kotor Ringan/Debu', 'Bau/Bakteri'],
                'is_active' => true,
            ],
            [
                'name' => 'Regular Clean (Warna Terang)',
                'slug' => 'regular-shoes-light',
                'description' => 'Pembersihan presisi untuk sneakers & casual warna cerah atau kombinasi warna. Menggunakan formula color-safe aktif guna mencegah kelunturan dan menjaga kecerahan warna.',
                'price' => 50000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Slip-on', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => ['Suede', 'Nubuck'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Bau/Bakteri'],
                'is_active' => true,
            ],
            [
                'name' => 'White Shoes Treatment',
                'slug' => 'white-shoes-treatment',
                'description' => 'Perawatan intensif khusus sepatu putih untuk semua material. Mengangkat kusam membandel serta memproteksi upper dan midsole agar kembali bersih dan segar.',
                'price' => 55000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Canvas Shoes', 'Sports', 'Slip-on'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit', 'Genuine Leather'],
                'unsuited_materials' => ['Suede'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Midsole Menguning'],
                'is_active' => true,
            ],
            [
                'name' => 'White Shoes Deep Clean & Whitening',
                'slug' => 'white-shoes-whitening',
                'description' => 'Paket komprehensif deep cleaning luar-dalam yang dipadukan dengan formula pencerah aktif untuk mengatasi noda kuning oksidasi membandel pada upper kanvas & sintetis.',
                'price' => 90000.00,
                'estimated_days' => 4,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit', 'Genuine Leather'],
                'unsuited_materials' => ['Suede', 'Nubuck'],
                'target_issues' => ['Midsole Menguning', 'Lumpur/Kotor Membandel'],
                'is_active' => true,
            ],
            [
                'name' => 'Suede & Nubuck Care (Warna Gelap)',
                'slug' => 'suede-care-treatment',
                'description' => 'Pembersihan khusus material suede dan nubuck gelap menggunakan dry-foam formula non-air dan sikat bulu kuda halus agar tekstur beludru tetap lembut dan bebas jamur.',
                'price' => 55000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on'],
                'supported_materials' => ['Suede', 'Nubuck'],
                'unsuited_materials' => ['Canvas', 'Mesh/Knit'],
                'target_issues' => ['Kotor Ringan/Debu', 'Jamur'],
                'is_active' => true,
            ],
            [
                'name' => 'Suede & Nubuck Care (Warna Terang)',
                'slug' => 'suede-care-light',
                'description' => 'Pembersihan teliti untuk suede dan nubuck warna cerah (beige, krem, pastel). Mencegah timbulnya noda air (water-spot) serta mengembalikan tekstur halus alami.',
                'price' => 65000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on'],
                'supported_materials' => ['Suede', 'Nubuck'],
                'unsuited_materials' => ['Canvas', 'Mesh/Knit'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Jamur'],
                'is_active' => true,
            ],
            [
                'name' => 'Leather Care & Conditioning',
                'slug' => 'leather-wax-conditioner',
                'description' => 'Perawatan premium sepatu kulit asli (formal & casual). Termasuk deep cleaning higienis, hidrasi leather conditioner, dan semir wax khusus untuk menjaga kelembutan serta kilau alami.',
                'price' => 55000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Boots', 'Loafers', 'Sneakers', 'Slip-on'],
                'supported_materials' => ['Genuine Leather'],
                'unsuited_materials' => ['Canvas', 'Suede', 'Nubuck', 'Mesh/Knit'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Bau/Bakteri'],
                'is_active' => true,
            ],
            [
                'name' => 'Air Jordan Special Care',
                'slug' => 'nike-air-jordan-care',
                'description' => 'Treatment spesialis sneakers koleksi Air Jordan. Pembersihan ekstra presisi pada toebox, midsole, outsole, wings logo, hingga padding pergelangan kaki.',
                'price' => 60000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Sports'],
                'supported_materials' => ['Genuine Leather', 'Synthetic'],
                'unsuited_materials' => [],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Bau/Bakteri'],
                'is_active' => true,
            ],
            [
                'name' => 'Heavy-Duty Boots Care',
                'slug' => 'boots-heavy-duty-care',
                'description' => 'Pembersihan mendalam sepatu boots outdoor dan kulit tebal (Red Wing, Timberland, Dr. Martens). Mengangkat kotoran membandel, conditioning kulit, dan sterilisasi antibakteri.',
                'price' => 80000.00,
                'estimated_days' => 4,
                'image_url' => null,
                'supported_types' => ['Boots'],
                'supported_materials' => ['Genuine Leather', 'Nubuck', 'Suede'],
                'unsuited_materials' => ['Canvas', 'Mesh/Knit'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Bau/Bakteri', 'Jamur'],
                'is_active' => true,
            ],
            [
                'name' => 'Vans Checkerboard Care',
                'slug' => 'vans-checkerboard-care',
                'description' => 'Pembersihan khusus motif catur Vans Checkerboard dengan teknik isolasi anti-bleeding agar pigmen warna hitam tidak merembes ke panel kanvas putih.',
                'price' => 55000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Canvas Shoes', 'Slip-on'],
                'supported_materials' => ['Canvas'],
                'unsuited_materials' => ['Suede', 'Nubuck'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel'],
                'is_active' => true,
            ],
            [
                'name' => 'Sandal & Birkenstock Care',
                'slug' => 'sandal-birkenstock-care',
                'description' => 'Perawatan higienis alas kaki kasual, slide, dan sandal Birkenstock. Membersihkan area cork footbed berpori, strap kulit/suede, serta outsole karet secara aman.',
                'price' => 65000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Slip-on'],
                'supported_materials' => ['Synthetic', 'Suede', 'Genuine Leather'],
                'unsuited_materials' => [],
                'target_issues' => ['Kotor Ringan/Debu', 'Bau/Bakteri', 'Jamur'],
                'is_active' => true,
            ],

            // KIDS SHOES
            [
                'name' => 'Kids Shoes Gentle Clean',
                'slug' => 'kids-shoes-cleaning',
                'description' => 'Pembersihan higienis khusus sepatu anak untuk seluruh material dan model. Menggunakan formula ramah anak tanpa residu tajam, lengkap dengan sterilisasi lampu UV.',
                'price' => 20000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Canvas Shoes', 'Slip-on', 'Sports'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => ['Suede', 'Nubuck'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Bau/Bakteri'],
                'is_active' => true,
            ],

            // WOMEN SHOES
            [
                'name' => 'Women Footwear Care (Flats & Heels)',
                'slug' => 'women-shoes-cleaning',
                'description' => 'Perawatan lembut untuk flat shoes, high heels, dan wedges berbahan sensitif. Membersihkan insole, upper, dan ornamen secara presisi tanpa merusak bentuk sepatu.',
                'price' => 45000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Loafers', 'Slip-on'],
                'supported_materials' => ['Synthetic', 'Genuine Leather', 'Canvas'],
                'unsuited_materials' => [],
                'target_issues' => ['Kotor Ringan/Debu', 'Bau/Bakteri'],
                'is_active' => true,
            ],

            // SHOES REPAIR
            [
                'name' => 'Jahit Sol Melingkar (Sol Stitching)',
                'slug' => 'shoes-repair-sol-stitch',
                'description' => 'Penjahitan sol melingkar menggunakan benang nilon berkekuatan tinggi berlapis lilin anti-putus. Menyatukan outsole dan upper secara kokoh dan rapi untuk pemakaian jangka panjang.',
                'price' => 30000.00,
                'estimated_days' => 4,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Suede', 'Nubuck', 'Genuine Leather', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => [],
                'target_issues' => ['Sol Mengelupas/Reglue'],
                'is_active' => true,
            ],
            [
                'name' => 'Reglue Press Outsole',
                'slug' => 'shoes-repair-reglue',
                'description' => 'Pengeleman ulang sol sepatu yang lepas atau menganga menggunakan bonding adhesive industri dan mesin press pneumatik terstandarisasi untuk daya rekat maksimal.',
                'price' => 45000.00,
                'estimated_days' => 4,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Suede', 'Nubuck', 'Genuine Leather', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => [],
                'target_issues' => ['Sol Mengelupas/Reglue'],
                'is_active' => true,
            ],
            [
                'name' => 'Paket Komplit Reglue & Jahit Sol',
                'slug' => 'shoes-repair-reglue-sol',
                'description' => 'Kombinasi komprehensif pengeleman ulang dengan adhesive primer berkekuatan tinggi serta penjahitan sol melingkar untuk perlindungan ganda anti-lepas.',
                'price' => 80000.00,
                'estimated_days' => 5,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Suede', 'Nubuck', 'Genuine Leather', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => [],
                'target_issues' => ['Sol Mengelupas/Reglue'],
                'is_active' => true,
            ],
            [
                'name' => 'Penggantian Outsole Baru',
                'slug' => 'shoes-repair-ganti-outsole',
                'description' => 'Penggantian tapak bawah sepatu yang aus, retak, atau licin dengan outsole karet baru berkualitas tinggi yang presisi dengan model dan ukuran sepatu Anda.',
                'price' => 100000.00,
                'estimated_days' => 7,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Suede', 'Nubuck', 'Genuine Leather', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => [],
                'target_issues' => ['Sol Mengelupas/Reglue'],
                'is_active' => true,
            ],

            // SHOES REPAINT / RECOLOUR
            [
                'name' => 'Recolour Canvas & Mesh/Knit',
                'slug' => 'shoes-repaint-canvas-mesh',
                'description' => 'Pengecatan ulang atau restorasi warna pudar untuk kain kanvas, mesh, dan rajut. Menggunakan cat pigmen fleksibel berbahan dasar air yang meresap tanpa membuat kaku.',
                'price' => 100000.00,
                'estimated_days' => 7,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Canvas Shoes', 'Slip-on', 'Sports'],
                'supported_materials' => ['Canvas', 'Mesh/Knit'],
                'unsuited_materials' => [],
                'target_issues' => ['Warna Pudar/Repaint'],
                'is_active' => true,
            ],
            [
                'name' => 'Repaint & Recolour Leather',
                'slug' => 'shoes-repaint-leather',
                'description' => 'Restorasi warna profesional untuk sepatu kulit asli maupun sintetis yang pudar atau tergores. Menghasilkan lapisan pelindung anti-retak bertampilan elegan.',
                'price' => 100000.00,
                'estimated_days' => 7,
                'image_url' => null,
                'supported_types' => ['Boots', 'Loafers', 'Sneakers', 'Slip-on'],
                'supported_materials' => ['Genuine Leather', 'Synthetic'],
                'unsuited_materials' => [],
                'target_issues' => ['Warna Pudar/Repaint'],
                'is_active' => true,
            ],
            [
                'name' => 'Recolour Suede & Nubuck',
                'slug' => 'shoes-repaint-suede-nubuck',
                'description' => 'Pewarnaan ulang bahan beludru suede dan nubuck dengan penetrator dye khusus agar pigmen meresap sempurna ke dalam serat tanpa menggumpalkan bulu halus.',
                'price' => 100000.00,
                'estimated_days' => 7,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on'],
                'supported_materials' => ['Suede', 'Nubuck'],
                'unsuited_materials' => [],
                'target_issues' => ['Warna Pudar/Repaint'],
                'is_active' => true,
            ],
            [
                'name' => 'Repaint Midsole & Edge Coating',
                'slug' => 'shoes-repaint-midsole',
                'description' => 'Pengecatan ulang sol samping (midsole) yang kusam, menguning berat, atau tergores menggunakan cat polimer elastis tahan tekukan saat melangkah.',
                'price' => 100000.00,
                'estimated_days' => 5,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Sports', 'Canvas Shoes', 'Slip-on'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit', 'Genuine Leather'],
                'unsuited_materials' => [],
                'target_issues' => ['Midsole Menguning', 'Warna Pudar/Repaint'],
                'is_active' => true,
            ],

            // SPECIAL TREATMENT
            [
                'name' => 'Unyellowing Midsole Treatment',
                'slug' => 'unyellowing-midsole',
                'description' => 'Proses de-oksidasi kimiawi aman yang dipadukan dengan pemaparan sinar UV terukur untuk mengembalikan warna putih bersih midsole karet yang menguning akibat oksidasi.',
                'price' => 60000.00,
                'estimated_days' => 4,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Sports', 'Canvas Shoes', 'Slip-on'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit', 'Genuine Leather'],
                'unsuited_materials' => [],
                'target_issues' => ['Midsole Menguning'],
                'is_active' => true,
            ],
            [
                'name' => 'Rewhitening Upper Treatment',
                'slug' => 'rewhitening-upper',
                'description' => 'Restorasi warna putih pada bagian upper sepatu yang kusam atau menguning. Mengembalikan kecerahan warna secara merata tanpa merusak serat material.',
                'price' => 55000.00,
                'estimated_days' => 4,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Sports', 'Canvas Shoes'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => ['Suede', 'Nubuck'],
                'target_issues' => ['Midsole Menguning', 'Lumpur/Kotor Membandel'],
                'is_active' => true,
            ],
        ];

        foreach ($services as $service) {
            Service::updateOrCreate(
                ['slug' => $service['slug']],
                $service
            );
        }
    }
}
