<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Updated with official SOLECRAFT Care Pricelist.
     */
    public function run(): void
    {
        $services = [
            // SHOES CLEANING REGULAR
            [
                'name' => 'Regular Shoes (Warna Gelap)',
                'slug' => 'regular-shoes-dark',
                'description' => 'Pembersihan menyeluruh khusus sneakers & casual warna gelap (hitam, navy, cokelat). Membersihkan upper, midsole, laces, plus parfum eksklusif & packing ziplock steril.',
                'price' => 45000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Slip-on', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => ['Suede', 'Nubuck'],
                'target_issues' => ['Kotor Ringan/Debu', 'Bau/Bakteri'],
                'is_active' => true,
            ],
            [
                'name' => 'Regular Shoes (Warna Terang)',
                'slug' => 'regular-shoes-light',
                'description' => 'Pembersihan presisi untuk sneakers & casual warna terang/colorful. Menggunakan formula color-safe untuk mencegah luntur dan mengembalikan kesegaran warna.',
                'price' => 50000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Slip-on', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => ['Suede', 'Nubuck'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Bau/Bakteri'],
                'is_active' => true,
            ],
            [
                'name' => 'White Shoes (Treatment Khusus)',
                'slug' => 'white-shoes-treatment',
                'description' => 'Treatment khusus sepatu putih semua material (All Material). Tarif berjenjang sesuai ukuran: Uk 30–35 (55K), Uk 35–40 (65K), Uk 40–45 (75K).',
                'price' => 55000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Canvas Shoes', 'Sports', 'Slip-on'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit', 'Genuine Leather'],
                'unsuited_materials' => ['Suede'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Midsole Menguning'],
                'is_active' => true,
            ],
            [
                'name' => 'White Shoes Whitening & Deep Clean',
                'slug' => 'white-shoes-whitening',
                'description' => 'Dikhususkan untuk upper sepatu yang menguning akibat noda & oksidasi membandel. Sudah include paket Deep Cleaning menyeluruh luar dan dalam.',
                'price' => 90000.00,
                'estimated_days' => 4,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit', 'Genuine Leather'],
                'unsuited_materials' => ['Suede', 'Nubuck'],
                'target_issues' => ['Midsole Menguning', 'Lumpur/Kotor Membandel'],
                'is_active' => true,
            ],
            [
                'name' => 'Suede & Nubuck Care Treatment',
                'slug' => 'suede-care-treatment',
                'description' => 'Pembersihan khusus material suede dan nubuck menggunakan foam non-air dan sikat bulu halus agar tekstur beludru tetap lembut, tidak kaku, dan bebas jamur. Gelap: 55K, Terang: 65K.',
                'price' => 55000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on'],
                'supported_materials' => ['Suede', 'Nubuck'],
                'unsuited_materials' => ['Canvas', 'Mesh/Knit'],
                'target_issues' => ['Kotor Ringan/Debu', 'Jamur'],
                'is_active' => true,
            ],
            [
                'name' => 'Suede Care (Warna Terang)',
                'slug' => 'suede-care-light',
                'description' => 'Pembersihan presisi suede warna terang (beige, krem, pastel). Bebas water-spot, tekstur tetap halus natural, dan warna kembali cerah segar.',
                'price' => 65000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on'],
                'supported_materials' => ['Suede', 'Nubuck'],
                'unsuited_materials' => ['Canvas', 'Mesh/Knit'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Jamur'],
                'is_active' => true,
            ],
            [
                'name' => 'Leather Care (Wax & Conditioner)',
                'slug' => 'leather-wax-conditioner',
                'description' => 'Treatment premium sepatu kulit (Include Wax & Conditioner). Regular Low: 55K, Regular High: 65K, Dr. Martens: 75K, Timberland: 75K.',
                'price' => 55000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Boots', 'Loafers', 'Sneakers', 'Slip-on'],
                'supported_materials' => ['Genuine Leather'],
                'unsuited_materials' => ['Canvas', 'Suede', 'Nubuck', 'Mesh/Knit'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Bau/Bakteri'],
                'is_active' => true,
            ],
            [
                'name' => 'Nike Air Jordan Special Care',
                'slug' => 'nike-air-jordan-care',
                'description' => 'Treatment spesialis sneakers Nike Air Jordan. Ekstra detail toebox, midsole, wings logo, dan outsole. Low: 60K, High: 70K.',
                'price' => 60000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Sports'],
                'supported_materials' => ['Genuine Leather', 'Synthetic'],
                'unsuited_materials' => [],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Bau/Bakteri'],
                'is_active' => true,
            ],
            [
                'name' => 'Boots Care Treatment',
                'slug' => 'boots-heavy-duty-care',
                'description' => 'Pembersihan mendalam sepatu boots kulit & outdoor. Regular: 80K, Timberland: 85K, Dr. Martens: 85K, Nubuck: 100K.',
                'price' => 80000.00,
                'estimated_days' => 4,
                'image_url' => null,
                'supported_types' => ['Boots'],
                'supported_materials' => ['Genuine Leather', 'Nubuck', 'Suede'],
                'unsuited_materials' => ['Canvas', 'Mesh/Knit'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Bau/Bakteri', 'Jamur'],
                'is_active' => true,
            ],
            [
                'name' => 'Vans Checkerboard Care',
                'slug' => 'vans-checkerboard-care',
                'description' => 'Perawatan khusus motif catur Vans Checkerboard dengan teknik anti-bleeding agar warna hitam tidak merembes ke putih. Uk 35–40: 55K, Uk 40–45: 60K.',
                'price' => 55000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Canvas Shoes', 'Slip-on'],
                'supported_materials' => ['Canvas'],
                'unsuited_materials' => ['Suede', 'Nubuck'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel'],
                'is_active' => true,
            ],
            [
                'name' => 'Sandal & Birkenstock Care',
                'slug' => 'sandal-birkenstock-care',
                'description' => 'Perawatan sandal & Birkenstock. Pembersihan cork footbed & strap khusus. Birkenstock Rubber: 65K, Birkenstock Suede: 75K.',
                'price' => 65000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Slip-on'],
                'supported_materials' => ['Synthetic', 'Suede', 'Genuine Leather'],
                'unsuited_materials' => [],
                'target_issues' => ['Kotor Ringan/Debu', 'Bau/Bakteri', 'Jamur'],
                'is_active' => true,
            ],

            // KIDS SHOES
            [
                'name' => 'Kids Shoes Cleaning',
                'slug' => 'kids-shoes-cleaning',
                'description' => 'Pembersihan higienis sepatu anak untuk semua bahan & model. Small: 20K, Medium: 25K, Regular: 30K. Sudah include all cleaning, parfume, packing ziplock steril.',
                'price' => 20000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Canvas Shoes', 'Slip-on', 'Sports'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => ['Suede', 'Nubuck'],
                'target_issues' => ['Kotor Ringan/Debu', 'Lumpur/Kotor Membandel', 'Bau/Bakteri'],
                'is_active' => true,
            ],

            // WOMEN SHOES
            [
                'name' => 'Women Shoes (Flats, Heels, Wedges)',
                'slug' => 'women-shoes-cleaning',
                'description' => 'Perawatan lembut sepatu wanita all cleaning & material. Flat Shoes: 45K, High Heels: 45K, Wedges: 50K. Include parfume, packing ziplock, estimasi 3–5 hari.',
                'price' => 45000.00,
                'estimated_days' => 3,
                'image_url' => null,
                'supported_types' => ['Loafers', 'Slip-on'],
                'supported_materials' => ['Synthetic', 'Genuine Leather', 'Canvas'],
                'unsuited_materials' => [],
                'target_issues' => ['Kotor Ringan/Debu', 'Bau/Bakteri'],
                'is_active' => true,
            ],

            // SHOES REPAIR
            [
                'name' => 'Shoes Repair - Jait Sol',
                'slug' => 'shoes-repair-sol-stitch',
                'description' => 'Penjahitan sol melingkar menggunakan benang nilon berlapis lilin anti-putus. Kuat, rapi, dan tahan lama. Rentang tarif pengerjaan: 30K – 100K.',
                'price' => 30000.00,
                'estimated_days' => 4,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Suede', 'Nubuck', 'Genuine Leather', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => [],
                'target_issues' => ['Sol Mengelupas/Reglue'],
                'is_active' => true,
            ],
            [
                'name' => 'Shoes Repair - Reglue Press',
                'slug' => 'shoes-repair-reglue',
                'description' => 'Pengeleman sol lepas atau mangap menggunakan adhesive primer berkualitas tinggi dan mesin press pneumatic. Bergaransi kuat. Tarif: 45K – 150K.',
                'price' => 45000.00,
                'estimated_days' => 4,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Suede', 'Nubuck', 'Genuine Leather', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => [],
                'target_issues' => ['Sol Mengelupas/Reglue'],
                'is_active' => true,
            ],
            [
                'name' => 'Shoes Repair - Reglue + Sol',
                'slug' => 'shoes-repair-reglue-sol',
                'description' => 'Paket kombinasi komplit pengeleman ulang sol dan jahit sol melingkar. Perlindungan ganda anti-mangap. Rentang tarif: 80K – 120K.',
                'price' => 80000.00,
                'estimated_days' => 5,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Suede', 'Nubuck', 'Genuine Leather', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => [],
                'target_issues' => ['Sol Mengelupas/Reglue'],
                'is_active' => true,
            ],
            [
                'name' => 'Shoes Repair - Ganti Outsole',
                'slug' => 'shoes-repair-ganti-outsole',
                'description' => 'Penggantian tapak outsole yang botak, retak, atau licin dengan outsole karet baru sesuai model sepatu. Rentang tarif: 100K – 400K.',
                'price' => 100000.00,
                'estimated_days' => 7,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on', 'Canvas Shoes', 'Sports'],
                'supported_materials' => ['Canvas', 'Suede', 'Nubuck', 'Genuine Leather', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => [],
                'target_issues' => ['Sol Mengelupas/Reglue'],
                'is_active' => true,
            ],

            // SHOES REPAINT / RECOLOUR
            [
                'name' => 'Shoes Repaint - Canvas & Mesh/Knit',
                'slug' => 'shoes-repaint-canvas-mesh',
                'description' => 'Pengecatan ulang atau ganti warna (recolour) bahan fabric Canvas, Mesh, atau Knit. Menggunakan cat akrilik fleksibel anti-kaku. Tarif: 100K – 300K.',
                'price' => 100000.00,
                'estimated_days' => 7,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Canvas Shoes', 'Slip-on', 'Sports'],
                'supported_materials' => ['Canvas', 'Mesh/Knit'],
                'unsuited_materials' => [],
                'target_issues' => ['Warna Pudar/Repaint'],
                'is_active' => true,
            ],
            [
                'name' => 'Shoes Repaint - Leather',
                'slug' => 'shoes-repaint-leather',
                'description' => 'Restorasi warna sepatu kulit asli atau sintetis yang pudar/baret. Finishing rapi, lentur, dan tahan retak. Rentang tarif: 100K – 350K.',
                'price' => 100000.00,
                'estimated_days' => 7,
                'image_url' => null,
                'supported_types' => ['Boots', 'Loafers', 'Sneakers', 'Slip-on'],
                'supported_materials' => ['Genuine Leather', 'Synthetic'],
                'unsuited_materials' => [],
                'target_issues' => ['Warna Pudar/Repaint'],
                'is_active' => true,
            ],
            [
                'name' => 'Shoes Repaint - Suede / Nubuck',
                'slug' => 'shoes-repaint-suede-nubuck',
                'description' => 'Pewarnaan ulang bahan beludru suede & nubuck dengan penetrator dye khusus agar bulu tidak kaku atau menggumpal. Rentang tarif: 100K – 400K.',
                'price' => 100000.00,
                'estimated_days' => 7,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Boots', 'Loafers', 'Slip-on'],
                'supported_materials' => ['Suede', 'Nubuck'],
                'unsuited_materials' => [],
                'target_issues' => ['Warna Pudar/Repaint'],
                'is_active' => true,
            ],
            [
                'name' => 'Shoes Repaint - Midsole',
                'slug' => 'shoes-repaint-midsole',
                'description' => 'Pengecatan ulang midsole yang baret parah atau teroksidasi berat. Menggunakan midsole paint elastis tahan tekukan. Rentang tarif: 100K – 150K.',
                'price' => 100000.00,
                'estimated_days' => 5,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Sports', 'Canvas Shoes', 'Slip-on'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit', 'Genuine Leather'],
                'unsuited_materials' => [],
                'target_issues' => ['Midsole Menguning', 'Warna Pudar/Repaint'],
                'is_active' => true,
            ],

            // SPECIAL TREATMENT
            [
                'name' => 'Unyellowing (Midsole)',
                'slug' => 'unyellowing-midsole',
                'description' => 'Treatment restorasi midsole karet yang menguning karena oksidasi menggunakan formula khusus & sinar UV. Dilihat dari tingkat kekuningan: Mulai 60K – 95K.',
                'price' => 60000.00,
                'estimated_days' => 4,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Sports', 'Canvas Shoes', 'Slip-on'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit', 'Genuine Leather'],
                'unsuited_materials' => [],
                'target_issues' => ['Midsole Menguning'],
                'is_active' => true,
            ],
            [
                'name' => 'Rewhitening (Upper Sepatu)',
                'slug' => 'rewhitening-upper',
                'description' => 'Restorasi warna putih pada bagian upper sepatu & midsole cleaning. Dilihat dari tingkat kekuningan bahan upper: Mulai 55K – 90K.',
                'price' => 55000.00,
                'estimated_days' => 4,
                'image_url' => null,
                'supported_types' => ['Sneakers', 'Sports', 'Canvas Shoes'],
                'supported_materials' => ['Canvas', 'Synthetic', 'Mesh/Knit'],
                'unsuited_materials' => ['Suede', 'Nubuck'],
                'target_issues' => ['Midsole Menguning', 'Lumpur/Kotor Membandel'],
                'is_active' => true,
            ],
        ];

        foreach ($services as $service) {
            Service::updateOrCreate(
                ['slug' => $service['slug']],
                $service
            );
        }
    }
}
